### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by Accacio** [cooklang/cook-in-c#1]
More of a question, do you plan using flex/bison?

**Comment by Seth-Harlaar** [comment]
I was not planning on it. Would be a good option though.

**Comment by Accacio** [comment]
There are two pages I found can be interesting about making flex/bison reentrant and creating an AST: http://wischik.com/lu/programmer/re-ast.html, https://lloydrochester.com/post/flex-bison/json-parse-ast/. Since we need this for multiple files
And for unicode classes in flex: https://lists.gnu.org/archive/html/help-flex/2005-01/msg00043.html

**Comment by Seth-Harlaar** [comment]
Hi Accacio, those are some good reads. I appreciate your passion for the project and I see you've started your own C parser. I'll consider what you've suggested here, and thanks for the input!
