### ISSUE TITLE
How to help ?

### ISSUE THREAD

**Issue by Net-Mist** [cooklang/cook-in-c#10]
Hello !
I find this project very interesting, and I will be willing to help. However I don't see any technical documentation or any dev discussion. 
What is the best way to get in touch with the dev team ?

**Comment by dubadub** [comment]
Hello 👋

Thanks for bringing it up. The project in early stages and doesn't have much docs yet and no formal development process setup. You can join our [Discord server](https://discord.gg/fUVVvUzEEK) and we can discuss next steps.
