### ISSUE TITLE
C linter

### ISSUE THREAD

**Issue by Net-Mist** [cooklang/cook-in-c#11]
Hello !
I would like to contribute to the project, but the C code doesn't seem to be formatted using a standard I know.
What are the linters and conventions used, if any ?
If no linters are used for the C code, would you agree to discuss so we can select one ? I strongly believed this is a necessary step before an external dev could contribute to the project

**Comment by dubadub** [comment]
Yes, I think it's a great idea. @Seth-Harlaar is maintaining the code, let's discuss with him when he's back.

**Comment by Seth-Harlaar** [comment]
Hi Net-Mist. I have not been using a linter so far, and have not selected one to be used. I would be happy to talk about some options with you. Feel free to send me message on discord, I am Boaty McBoatface#3609, or a general message in the discord server.

**Comment by Net-Mist** [comment]
Ok, let's do that.
I will update this issue after we reach a decision to keep track of it

**Comment by sebastieni-cs** [comment]
see PR https://github.com/cooklang/cooklang-c/pull/21

**Comment by Seth-Harlaar** [comment]
Me and @Net-Mist talked about this a couple of days ago, but I thought it would be good to discuss publicly. I figured we should avoid running the linter on the any of the automatically generated files. Net-Mist agreed.

**Comment by Accacio** [comment]
we should create a specific channel for the c development and make a poll for the formatting style

**Comment by Net-Mist** [comment]
Good idea !

**Comment by dubadub** [comment]
Created one for C https://discord.com/channels/942045537463590943/956115835511009281

**Comment by Net-Mist** [comment]
Done. See
* https://github.com/cooklang/cooklang-c/pull/21
* https://github.com/cooklang/cooklang-c/pull/30
* https://github.com/cooklang/cooklang-c/pull/31
