### ISSUE TITLE
lex.yy.h status

### ISSUE THREAD

**Issue by Net-Mist** [cooklang/cook-in-c#13]
The file `lex.yy.h` is removed when running `make full_clean` and no command in the makefile seems to regenerate it. (for info, the `flex -Ca` command only generate the `lex.yy.c` file)
Moreover, this file doesn't seem to be included anywhere in the code.
What is it status ? Should it be removed ?

**Comment by Seth-Harlaar** [comment]
This is a file that is necessary when the user is only using flex I believe. I don't think it is necessary with Bison, and can be safely removed. I will update the repository to reflect this.

**Comment by Net-Mist** [comment]
ok, I made a PR for file suppression : https://github.com/cooklang/cooklang-c/pull/20
