### ISSUE TITLE
Error in tests.yaml file

### ISSUE THREAD

**Issue by Net-Mist** [cooklang/cook-in-c#14]
Hello,
I'm in the process of rewriting the python tests to make them more pythonic. I now have some tests failing, because of the way python parse the yaml file. I believe this may be a issue in the design of the test.yaml file that need to be addressed:

the `metadata` field seems to be a dictionary field. When empty it is `[]`, but I think it should be `{}`. Except if I'm missing something ?

**Comment by Seth-Harlaar** [comment]
I didn't write the test.yaml file, and I wouldn't consider myself an expert on yaml, but I have no issue loading in the tests using the python package yaml, and the command `yaml.safe_load(test_file)`

**Comment by Net-Mist** [comment]
The problem is not loading the yaml file but checking the output of the parser with the content of the file. The current tests don't check the type of the variable, so the tests are passing. But now that I'm writing more strict tests, they are failing.

I agree, this is a more general issue that doesn't only concern this repo. For now I will keep this issue open and try to discuss this point with @dubadub . I will close it after his feedback

**Comment by dubadub** [comment]
@Net-Mist good catch. I agree that metadata should be a dictionary, not an array in canonical tests definition. I made the change https://github.com/cooklang/spec/commit/cacb4f23bd72b6abdc669a8cf979498fe4164a55.

**Comment by sebastieni-cs** [comment]
Cool ! Thanks :)
The changes will be reflected in this repo with this PR : https://github.com/cooklang/cooklang-c/pull/15

**Comment by Seth-Harlaar** [comment]
PR: #15 was merged to main.
