### ISSUE TITLE
Repo organisation

### ISSUE THREAD

**Issue by Net-Mist** [cooklang/cook-in-c#22]
Hello @dubadub  @Seth-Harlaar 

There are several points I would like to address with you, because right now I'm not feeling super easy regarding this repo organization.
* It seems that right now, this repo is going through big changes, with creation of other git sub-repo for specific language (python in this case). Although on paper it makes a lot of sense, I hope the drawbacks of this decision are also very clear for you . Multi-repo organization can quickly become a pain to manage, and it is also way more difficult for external contributor to work on this project. For instance, in my case, right now I need to fork also the second repository, update my fork of the main repo to link it to the fork of the subrepo, and be careful to never push this commit when contributing to the original repo.
* Also I'm a bit sad to see that these important changes were pushed on master without discussion with the community (well, we are not a lot right now but still ^^) I think the main maintainers of a repo should respect the same coding convention than community members, by opening PR and waiting a few days for feedback before merging on master.
* This last point is especially true given the fact that the current split between both repo doesn't seem to be well defined. Currently the python repo is a big copy-pasting of this repo, and this repo still contains python code for testing and packaging... I think it would have been way cleaner to work on this multi-repo setup in a branch and wait for it to be ready before merging on master. (well, more specifically work on 2 branches, one in both repo, been careful that both branch stay in sync, and merge both at the same time)

Also, now that I think about it, I'm not sure to understand why the python repo is a dependence of the C repo. Shouldn't it be the other way around, with the C repo autonomous and the python repo having the C version as dependency ?

**Comment by dubadub** [comment]
Hey @Net-Mist,

Thanks for sharing your concerns. I absolutely agree with all your three points. Right now we don't have any process in place as there's only one contributor in this repo (@Seth-Harlaar) and its in early-ish stage. This makes its hard for other people to step in and help. If you don't mind joining our forces, I'll add you as a maintainer and then three of us agree on process (goals, roadmap, reviews, etc). How does this sound? 

Also linking @Accacio as I've seen his interest in project too.

**Comment by Net-Mist** [comment]
Hey @dubadub 

Thanks a lot for the proposition, I would be happy to become a maintainer of this repo.

I think it's important to have our discussion somewhere public, so anyone could join and add his own opinion.

Maybe we could open one issue which will be a To Do list of all the tasks that need to be done. Then, for every tasks, we can open another issue to discuss it and clearly define the spec of the implementation. 

Another solution, maybe a bit too much for now but that can be interesting if the project become bigger is to use the "project" feature of Github. We could create a Kanban board  (using the project tab on github https://github.com/cooklang/cooklang-c/projects) with 5 columns:
* Backlog: list of all the tasks that need to be done at some point, but not yet clearly defined
* To Do: list of all the tasks clearly defined that are not started yet
* Doing: list of tasks with open Pull Request in draft mode
* Code Review: list of tasks with corresponding Pull Request done and waiting for review
* Done: tasks with corresponding PR merged

What do you think ?

**Comment by dubadub** [comment]
Fantastic! Thank you so much @Net-Mist. I sent you an invite. The plan forward sounds good to me. Tomorrow I'll describe in an issue what we have in mind. I'm totally for trying projects if you like.

**Comment by dubadub** [comment]
@Net-Mist @Seth-Harlaar I outlined my thinking here https://github.com/cooklang/cooklang-c/issues/23. Feel free to offer your ideas and add your comments.

**Comment by Seth-Harlaar** [comment]
Going to close the issue since the issues outlined here are being discussed and addressed in #23 .
