### ISSUE TITLE
Restructure README and CONTRIBUTING pages. README should show how C-parser users can use it and cover input/output.  We don't expect them to know anything about flex/bison. They just use precompiled version. CONTRIBUTING page should reference how people could make changes to C-parser project itself. There we cover flex/bison and friends.

### ISSUE THREAD

**Issue by Seth-Harlaar** [cooklang/cook-in-c#29]

**Comment by Seth-Harlaar** [comment]
Hi all. I have made some changes to the CONTRIBUTING and am asking for input. Is there anything missing from either the readme or the contributing page? Anything unclear?
Also, the readme page mainly talks about using the python module to use the C parser. Since we now have a separate repo for the python module, should we move the readme of cooklang-c to cooklang-py? I believe it would make sense.

**Comment by Net-Mist** [comment]
I believed at some point it would make sense. But for now, as we don't have C tests, I think the repo should stay like this.
But as soon as the testing is done in C, then I agree, the python part and the Readme should move to the other repo

**Comment by Seth-Harlaar** [comment]
Going to close issue for now and it can be reopened later.
