### ISSUE TITLE
Tests Failing

### ISSUE THREAD

**Issue by Accacio** [cooklang/cook-in-c#6]
https://github.com/cooklang/cook-in-c/blob/9a5fba094f7d7043bc5ada27da47455b5aabcdc0/.github/workflows/test.yml#L16

The test fail because the runner has no root privileges when running the apt-get line

**Comment by Seth-Harlaar** [comment]
Ok, thank you for the note. I have some changes coming to the makefile and general file structure sometime soon, so I will tackle that problem when I push those changes. I'll also take a look at your PR.
